#selenium:
#  chromedriver:
#    path: C:/Users/skrheem/IdeaProjects/Train/chromedriver-win64/chromedriver.exe

# 서버 포트 번호
server:
  port: 8093
  ssl:
    enabled: false
    key-store: file:///C:/Java/jdk-11.0.15/bin/keystore.p12
    key-store-password: 990922
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  # 콘솔 ansi 색상
  output:
    ansi:
      enabled: always

  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/views/
    suffix: .html

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/traindb?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: train
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect: org.hibernate.dialect.MariaDBDialect

# 페이징 관련 세팅값
app:
  pagination:
    # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지를 표시
    write_pages: 10
    # 기본 page_rows 값. 한 '페이지'에 몇개의 글을 리스트 할것인가?
    page_rows: 10

kakao:
  client:
    id: b45dc756bf1f71d465dbf93f791be727
    secret: ZwJupmVkWPJM9UiAR1M5ICGAwih2fLd5
  redirect:
    url: http://localhost:8093/kakao/callback


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
